test-isolate-address: test-isolate-address.cxx
	g++ test-isolate-address.cxx -o test-isolate-address

clean: FORCE
	if [ -e test-isolate-address ]; then rm test-isolate-address; fi

# Don't remove this line
FORCE:
